baseURL = "https://interfiber.github.io/starbuild/"
languageCode = "en-us"
title = "Starbuild"
theme = "techdoc"
[params]
    description = "A fast plugin based build system written in lua"
    github_repository = "https://github.com/Interfiber/starbuild"
    menu_style = "open-menu"
[menu]