local init = {}
init.Bootstrap = function ()
    print("generating starbuild.lua...")
    local config = io.open("starbuild.lua", "w+")
    io.output(config)
    io.write("-- Starbuild config file, generated by 'starbuild init'\n")
    io.write("-- all config must be in the Config function\n")
    io.write("local star = {}\n")
    io.write("-- when starbuild runs this function, it will pass in a table with starbuild functions in it.\n")
    io.write("function star.Config(starbuild)\n")
    io.write("       -- configure default plugins.\n")
    io.write("       -- set plugins. Uncomment the one for your language.\n")
    io.write("       -- C/C++\n")
    io.write("       -- starbuild.LoadPlugin('DEFAULT_CPP')\n")
    io.write("       -- starbuild.RunPluginTrigger('CPPBuild', { 'foo.hpp', 'foo.cpp' })\n")
    io.write("end\n")
    io.write("-- return config\nreturn star")
    io.close()

end
return init