-- Starbuild config file, generated by 'starbuild init'
-- all config must be in the Config function
local star = {}
-- when starbuild runs this function, it will pass in a table with starbuild functions in it.
function star.Config(starbuild)
       -- configure default plugins.
       -- set plugins. Uncomment the one for your language.
       starbuild.LoadPlugin("DEFAULT_C")
       starbuild.RunPluginTrigger("C", "CBuild", { 'test.c' })
end
-- return config
return star